In [2]:
import numpy as np
import os
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression 


In [4]:
os.chdir("C:\\Users\\SADHANA\\OneDrive\\Documents\\Desktop\\PYTHON\\Jupyter Notebook\\CSV") 
data=pd.read_csv("salary.csv")

In [5]:
data

Salary  Expenditure
0       5           25
1       1            5
2       2            7
3       1            8

In [8]:
x=data[["Salary"]]
y=data["Expenditure"]

In [9]:
lr=LinearRegression()
lr.fit(x,y)

LinearRegression()

In [10]:
predict=np.array([[3]])
predicted=lr.predict(predict)


C:\Users\SADHANA\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [11]:
predicted

array([14.79069767])

In [12]:
data1=pd.read_csv("week.csv")

In [13]:
data1

Week  Sales in thousands
0     1                   1
1     2                   3
2     3                   4
3     4                   8

In [16]:
x=data1[["Week"]]
y=data1["Sales in thousands"]

In [17]:
lr=LinearRegression()
lr.fit(x,y)

LinearRegression()

In [18]:
find=np.array([[7]])
found=lr.predict(find)

C:\Users\SADHANA\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [19]:
found

array([13.9])

In [20]:
data2=pd.read_csv("sales.csv")

In [21]:
data2

X1  X2   Y
0   1   4   1
1   2   5   6
2   3   8   8
3   4   2  12

In [24]:
x=data2[['X1','X2']]
y=data2['Y']

In [26]:
lr=LinearRegression()
lr.fit(x,y)

LinearRegression()

In [27]:
guess=np.array([[5,9]])
gussed=lr.predict(guess)

C:\Users\SADHANA\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [28]:
gussed

array([15.22677596])

In [29]:
data3=pd.read_csv("purchase.csv")

In [30]:
data3

salary  purchase
0      40         0
1      50         0
2      38         0
3      60         1
4      65         1

In [31]:
x=data3[['salary']]
y=data3['purchase']

In [32]:
lr=LinearRegression()
lr.fit(x,y)

LinearRegression()

In [35]:
sale=np.array([[80]])
sold=int(lr.predict(sale))

C:\Users\SADHANA\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\SADHANA\AppData\Local\Temp\ipykernel_5832\3948595120.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  sold=int(lr.predict(sale))


In [36]:
sold

1

In [37]:
data4=pd.read_csv('student.csv')

In [38]:
data4

name  m1  m2  m3  hrs  performance
0  damon  89  65  89    8            1
1  elena  14  60  13    4            0
2   rose  56  57  45    6            1
3    max  12  15  34    2            0

In [40]:
x=data4[['m1','m2','m3','hrs']]
y=data4['performance']

In [41]:
lr=LinearRegression()
lr.fit(x,y)

LinearRegression()

In [42]:
mark=np.array([[11,12,13,1]])
got=int(lr.predict(mark))

C:\Users\SADHANA\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\SADHANA\AppData\Local\Temp\ipykernel_5832\2028797622.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  got=int(lr.predict(mark))


In [44]:
got

0